name: csvwriter
description: Lightweight Dart package to write CSV data to a StringSink. Supports and extends RFC 4180.
version: 1.0.0
homepage: https://github.com/d-markey/csvwriter

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
