name: csvwriter
description: Lightweight, cross-platform Dart package to write CSV data to a `StringSink`. Supports and extends RFC 4180.
version: 1.3.0
homepage: https://github.com/d-markey/csvwriter

environment:
  sdk: ">=2.12.0 <4.0.0"

# dependencies:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  js: ^0.6.7
